[build]
  command = "npm run build"
  publish = "dist"

# ✅ Redirect all routes to index.html (for React Router / Vite SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'none';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# ✅ Optional: Cache assets aggressively (good for Vite build)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
